window.COPY = {
  en: {
    home: "Discover",
    stories: "Stories",
    timeline: "Timeline",
    book: "The journal",
    map: "The map",
    gallery: "Gallery",
    people: "The people",
    games: "Travel games",
    social: "On social",
    saved: "Saved stories",
    more: "More",
    random: "Surprise me",
    journey: "A FAMILY. A HOME ON WHEELS. AN OPEN ROAD.",
    hero: "Gutman’s<br>Life Journey",
    motto:
      "Some journeys change the scenery.<br>This one changes what home means.",
    explore: "Explore the stories",
    years: "years in the archive",
    storiesCount: "stories collected",
    placesCount: "mapped places",
    strip: "Live with memories, not dreams.",
    collections: "Follow your curiosity",
    collectionsEye: "NOT JUST THE HIGHLIGHTS",
    funny: "The funny moments",
    hard: "The hard days",
    views: "The extraordinary views",
    collectionFunny: "Plans change. Laughter stays.",
    collectionHard: "The part beyond the postcard.",
    collectionViews: "A little perspective, a lot of wonder.",
    daily: "STORY OF THE DAY",
    readStory: "Read the story",
    latest: "Notes from the road",
    allStories: "All stories",
    bookEye: "THE GUTMAN JOURNAL",
    bookTitle: "A home is more<br>than four walls.",
    bookIntro:
      "A family adventure, shaped by mountain roads, improvised plans and the people who turn up at just the right moment.",
    readBook: "Open the journal",
    storyIntro:
      "Big adventures and ordinary days, gathered from the family’s own accounts.",
    search: "Search places, people, moments…",
    allCountries: "Every country",
    allTopics: "Every experience",
    newest: "Newest first",
    oldest: "Oldest first",
    allYears: "Every year",
    reset: "Reset filters",
    results: "stories",
    loadMore: "More from the road",
    noResults: "No stories here yet.",
    tryAgain: "Try a different place or experience.",
    dateUnknown: "Date unverified",
    placeUnknown: "Along the way",
    published: "Published",
    travelDate: "Travel date",
    bothSources: "Instagram + Facebook",
    original: "Original post",
    sourceExcerpt: "From the original",
    editorial: "An editorial retelling based on the family’s public account.",
    save: "Save story",
    unsave: "Remove bookmark",
    savedToast: "Added to your reading list",
    removedToast: "Removed from your reading list",
    copyLink: "Copy link",
    copied: "Story link copied",
    copyFailed: "The story address is in your browser’s address bar.",
    timelineIntro:
      "One journey, many chapters. Publication dates and explicitly stated travel dates stay separate.",
    galleryIntro: "The places, faces and small details along the way.",
    bookDescription:
      "An illustrated editorial journal drawn from the Gutmans’ public stories. Not a first-person memoir or a text written by the family.",
    contents: "Contents",
    chapter: "Chapter",
    previous: "Previous chapter",
    next: "Next chapter",
    sources: "Source stories",
    print: "Print the journal",
    bookNote:
      "This edition draws on the collected stories. The Facebook archive is still being completed; it is not yet a complete life history.",
    mapIntro:
      "Places documented in the stories. Markers identify towns or landmarks, not campsites or a recorded driving route.",
    mapLoading: "Loading map…",
    mapError: "The map could not load. The place list is still available.",
    mapLocal:
      "The interactive map needs the hosted website. You can still explore the stories by place below.",
    mapRetry: "Retry map",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    viewPlace: "Explore these stories",
    peopleIntro: "The heart of the journey was never just the destination.",
    gamesIntro: "A small detour for curious travelers.",
    quiz: "Road-trip quiz",
    memory: "Postcard pairs",
    question: "Question",
    score: "Score",
    correct: "Exactly right.",
    incorrect: "A different turn this time.",
    nextQuestion: "Next question",
    playAgain: "Play again",
    quizFinish: "You made it to the end of the road.",
    moves: "Moves",
    pairs: "Pairs",
    memoryWin: "Every postcard found its traveling companion.",
    socialIntro: "The original journey, shared on Instagram and Facebook.",
    ranking: "Most viewed",
    rankingUnavailable: "A trustworthy most-viewed ranking is not available.",
    rankingNote:
      "The collected pages do not provide consistent view counts across both platforms. Likes, comments and views are different measures, so this site does not invent a leaderboard.",
    visitInstagram: "Visit Instagram",
    visitFacebook: "Visit Facebook",
    coverage: "Archive coverage",
    coverageNote:
      "All 213 Instagram post pages listed during collection were captured. Facebook coverage is partial. Cross-platform duplicates are merged when the evidence is strong; ambiguous matches stay separate.",
    pending: "Source text incomplete",
    pendingNote:
      "Only a preview of this post was accessible. The full story has not been reconstructed.",
    complete: "readable stories",
    pendingCount: "incomplete previews",
    merged: "cross-platform stories",
    savedIntro: "A few pages to come back to. Stored only in this browser.",
    savedEmpty: "Your reading list is still open.",
    savedHint: "Bookmark a story that stays with you.",
    footer:
      "An independent editorial tribute to a family’s life on the road. Stories and photographs belong to their original creators.",
    footerNote: "Preview edition · Source-linked · No tracking",
    archiveStatus: "Archive status",
    waterfalls: "Waterfalls",
    hiking: "Hiking",
    learning: "Learning",
    truck: "Life in Alma",
    cities: "City days",
    unknown: "Unspecified",
    chapterEmpty: "The next chapter is being prepared.",
    emptyGallery: "No photographs match this selection.",
  },
  he: {
    home: "לגלות",
    stories: "הסיפורים",
    timeline: "ציר הזמן",
    book: "ספר המסע",
    map: "המפה",
    gallery: "גלריה",
    people: "האנשים",
    games: "משחקי דרך",
    social: "ברשתות",
    saved: "סיפורים שמורים",
    more: "עוד",
    random: "הפתעה בדרך",
    journey: "משפחה. בית על גלגלים. דרך פתוחה.",
    hero: "מסע החיים<br>של משפחת גוטמן",
    motto: "יש מסעות שמשנים את הנוף.<br>זה מסע שמשנה את המשמעות של בית.",
    explore: "לגלות את הסיפורים",
    years: "שנים בארכיון",
    storiesCount: "סיפורים שנאספו",
    placesCount: "מקומות על המפה",
    strip: "לחיות עם זיכרונות, לא רק עם חלומות.",
    collections: "ללכת בעקבות הסקרנות",
    collectionsEye: "לא רק הרגעים המושלמים",
    funny: "הרגעים המצחיקים",
    hard: "הימים הקשים",
    views: "הנופים המדהימים",
    collectionFunny: "התוכניות משתנות. הצחוק נשאר.",
    collectionHard: "הסיפור שמאחורי הגלויה.",
    collectionViews: "קצת פרופורציות, הרבה פליאה.",
    daily: "הסיפור של היום",
    readStory: "לקריאת הסיפור",
    latest: "רשימות מהדרך",
    allStories: "כל הסיפורים",
    bookEye: "היומן של משפחת גוטמן",
    bookTitle: "בית הוא יותר<br>מארבעה קירות.",
    bookIntro:
      "הרפתקה משפחתית בין דרכי הרים, תוכניות מאולתרות ואנשים שמופיעים בדיוק ברגע הנכון.",
    readBook: "לפתוח את היומן",
    storyIntro: "הרפתקאות גדולות וימים רגילים, מתוך הסיפורים של המשפחה עצמה.",
    search: "חיפוש מקומות, אנשים ורגעים…",
    allCountries: "כל המדינות",
    allTopics: "כל החוויות",
    newest: "מהחדש לישן",
    oldest: "מהישן לחדש",
    allYears: "כל השנים",
    reset: "איפוס סינון",
    results: "סיפורים",
    loadMore: "עוד מהדרך",
    noResults: "עדיין אין כאן סיפורים.",
    tryAgain: "נסו מקום או חוויה אחרים.",
    dateUnknown: "התאריך לא אומת",
    placeUnknown: "אי שם בדרך",
    published: "פורסם",
    travelDate: "תאריך המסע",
    bothSources: "אינסטגרם + פייסבוק",
    original: "הפוסט המקורי",
    sourceExcerpt: "מתוך המקור",
    editorial: "עיבוד סיפורי המבוסס על הפרסום הציבורי של המשפחה.",
    save: "שמירת סיפור",
    unsave: "הסרת סימנייה",
    savedToast: "נוסף לרשימת הקריאה",
    removedToast: "הוסר מרשימת הקריאה",
    copyLink: "העתקת קישור",
    copied: "הקישור הועתק",
    copyFailed: "כתובת הסיפור מופיעה בשורת הכתובת בדפדפן.",
    timelineIntro:
      "מסע אחד, פרקים רבים. תאריכי הפרסום ותאריכי הטיול שנכתבו במפורש מוצגים בנפרד.",
    galleryIntro: "המקומות, הפנים והפרטים הקטנים שבדרך.",
    bookDescription:
      "יומן מסע מאויר בעריכה עצמאית, המבוסס על הסיפורים הציבוריים של משפחת גוטמן. אינו ספר זיכרונות בגוף ראשון או טקסט שנכתב בידי המשפחה.",
    contents: "תוכן העניינים",
    chapter: "פרק",
    previous: "לפרק הקודם",
    next: "לפרק הבא",
    sources: "הסיפורים שבבסיס הפרק",
    print: "הדפסת היומן",
    bookNote:
      "מהדורה זו מבוססת על הסיפורים שנאספו. ארכיון פייסבוק עדיין בתהליך השלמה; זה עדיין אינו סיפור חיים מלא.",
    mapIntro:
      "מקומות המתועדים בסיפורים. הסמנים מציינים יישובים ואתרים, לא מקומות לינה או מסלול נהיגה שנמדד.",
    mapLoading: "המפה נטענת…",
    mapError: "לא ניתן לטעון את המפה. רשימת המקומות עדיין זמינה.",
    mapLocal:
      "המפה האינטראקטיבית זמינה באתר המקוון. אפשר עדיין לעיין בסיפורים לפי מקום ברשימה למטה.",
    mapRetry: "טעינת המפה מחדש",
    zoomIn: "התקרבות",
    zoomOut: "התרחקות",
    viewPlace: "לסיפורים מהמקום",
    peopleIntro: "הלב של המסע מעולם לא היה רק היעד.",
    gamesIntro: "סטייה קטנה מהדרך למטיילים סקרנים.",
    quiz: "חידון מסע",
    memory: "זוגות של גלויות",
    question: "שאלה",
    score: "ניקוד",
    correct: "בדיוק נכון.",
    incorrect: "הפעם פנינו לכיוון אחר.",
    nextQuestion: "לשאלה הבאה",
    playAgain: "לשחק שוב",
    quizFinish: "הגעתם לסוף הדרך.",
    moves: "מהלכים",
    pairs: "זוגות",
    memoryWin: "כל גלויה מצאה את השותפה שלה למסע.",
    socialIntro: "המסע המקורי, כפי ששותף באינסטגרם ובפייסבוק.",
    ranking: "הנצפים ביותר",
    rankingUnavailable: "אין עדיין דירוג אמין של הפוסטים הנצפים ביותר.",
    rankingNote:
      "בעמודים שנאספו אין נתוני צפייה עקביים משתי הפלטפורמות. לייקים, תגובות וצפיות הם מדדים שונים, ולכן האתר אינו ממציא דירוג.",
    visitInstagram: "לאינסטגרם",
    visitFacebook: "לפייסבוק",
    coverage: "מצב הארכיון",
    coverageNote:
      "נאספו כל 213 עמודי הפוסטים שהופיעו באינסטגרם בזמן האיסוף. הכיסוי של פייסבוק חלקי. כפילויות בין הרשתות אוחדו כאשר הזיהוי ברור; התאמות לא ודאיות נשארו נפרדות.",
    pending: "טקסט המקור חלקי",
    pendingNote:
      "רק תצוגה מקדימה של הפוסט הייתה נגישה. הסיפור המלא עדיין לא שוחזר.",
    complete: "סיפורים לקריאה",
    pendingCount: "תצוגות חלקיות",
    merged: "סיפורים בשתי הרשתות",
    savedIntro: "כמה עמודים לחזור אליהם. נשמרים רק בדפדפן הזה.",
    savedEmpty: "רשימת הקריאה עדיין פתוחה.",
    savedHint: "שמרו סיפור שנשאר איתכם.",
    footer:
      "מחווה סיפורית עצמאית לחיי משפחה בדרכים. הסיפורים והתצלומים שייכים ליוצריהם המקוריים.",
    footerNote: "מהדורת תצוגה מקדימה · קישורים למקורות · ללא מעקב",
    archiveStatus: "מצב הארכיון",
    waterfalls: "מפלים",
    hiking: "טיולים ברגל",
    learning: "לומדים בדרך",
    truck: "החיים באלמה",
    cities: "ימים בעיר",
    unknown: "לא צוין",
    chapterEmpty: "הפרק הבא נמצא בעריכה.",
    emptyGallery: "אין תמונות שמתאימות לבחירה.",
  },
  es: {
    home: "Descubrir",
    stories: "Historias",
    timeline: "Cronología",
    book: "El diario",
    map: "El mapa",
    gallery: "Galería",
    people: "Las personas",
    games: "Juegos de viaje",
    social: "En redes",
    saved: "Guardados",
    more: "Más",
    random: "Sorpréndeme",
    journey: "UNA FAMILIA. UN HOGAR SOBRE RUEDAS. UN CAMINO ABIERTO.",
    hero: "Gutman’s<br>Life Journey",
    motto:
      "Hay viajes que cambian el paisaje.<br>Este cambia el significado de hogar.",
    explore: "Explorar las historias",
    years: "años en el archivo",
    storiesCount: "historias recopiladas",
    placesCount: "lugares en el mapa",
    strip: "Vivir con recuerdos, no solo con sueños.",
    collections: "Sigue tu curiosidad",
    collectionsEye: "NO SOLO LOS MEJORES MOMENTOS",
    funny: "Los momentos divertidos",
    hard: "Los días difíciles",
    views: "Las vistas extraordinarias",
    collectionFunny: "Los planes cambian. La risa queda.",
    collectionHard: "La historia detrás de la postal.",
    collectionViews: "Un poco de perspectiva, mucho asombro.",
    daily: "HISTORIA DEL DÍA",
    readStory: "Leer la historia",
    latest: "Notas del camino",
    allStories: "Todas las historias",
    bookEye: "EL DIARIO DE LOS GUTMAN",
    bookTitle: "Un hogar es más<br>que cuatro paredes.",
    bookIntro:
      "Una aventura familiar entre caminos de montaña, planes improvisados y personas que llegan justo a tiempo.",
    readBook: "Abrir el diario",
    storyIntro:
      "Grandes aventuras y días cotidianos, reunidos a partir de los relatos de la familia.",
    search: "Buscar lugares, personas, momentos…",
    allCountries: "Todos los países",
    allTopics: "Todas las experiencias",
    newest: "Más recientes",
    oldest: "Más antiguas",
    allYears: "Todos los años",
    reset: "Restablecer filtros",
    results: "historias",
    loadMore: "Más del camino",
    noResults: "Todavía no hay historias aquí.",
    tryAgain: "Prueba otro lugar o experiencia.",
    dateUnknown: "Fecha sin verificar",
    placeUnknown: "En el camino",
    published: "Publicado",
    travelDate: "Fecha del viaje",
    bothSources: "Instagram + Facebook",
    original: "Publicación original",
    sourceExcerpt: "Del original",
    editorial:
      "Una versión editorial basada en el relato público de la familia.",
    save: "Guardar historia",
    unsave: "Quitar marcador",
    savedToast: "Añadida a tu lista de lectura",
    removedToast: "Quitada de tu lista de lectura",
    copyLink: "Copiar enlace",
    copied: "Enlace copiado",
    copyFailed: "La dirección de la historia está en la barra del navegador.",
    timelineIntro:
      "Un viaje, muchos capítulos. Las fechas de publicación y las fechas explícitas del viaje se mantienen separadas.",
    galleryIntro: "Los lugares, las caras y los pequeños detalles del camino.",
    bookDescription:
      "Un diario editorial ilustrado basado en los relatos públicos de los Gutman. No son memorias en primera persona ni un texto escrito por la familia.",
    contents: "Índice",
    chapter: "Capítulo",
    previous: "Capítulo anterior",
    next: "Capítulo siguiente",
    sources: "Historias de origen",
    print: "Imprimir el diario",
    bookNote:
      "Esta edición se basa en las historias recopiladas. El archivo de Facebook sigue incompleto; todavía no es una historia de vida completa.",
    mapIntro:
      "Lugares documentados en las historias. Los marcadores indican ciudades o paisajes, no campamentos ni una ruta GPS.",
    mapLoading: "Cargando el mapa…",
    mapError:
      "No se pudo cargar el mapa. La lista de lugares sigue disponible.",
    mapLocal:
      "El mapa interactivo necesita el sitio web alojado. Puedes explorar las historias por lugar en la lista.",
    mapRetry: "Reintentar mapa",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    viewPlace: "Explorar estas historias",
    peopleIntro: "El corazón del viaje nunca fue solo el destino.",
    gamesIntro: "Un pequeño desvío para viajeros curiosos.",
    quiz: "Trivia del camino",
    memory: "Parejas de postales",
    question: "Pregunta",
    score: "Puntos",
    correct: "Exactamente.",
    incorrect: "Esta vez tomamos otro camino.",
    nextQuestion: "Siguiente pregunta",
    playAgain: "Jugar otra vez",
    quizFinish: "Llegaste al final del camino.",
    moves: "Movimientos",
    pairs: "Parejas",
    memoryWin: "Cada postal encontró su compañera de viaje.",
    socialIntro: "El viaje original, compartido en Instagram y Facebook.",
    ranking: "Más vistos",
    rankingUnavailable:
      "Todavía no hay una clasificación fiable por visualizaciones.",
    rankingNote:
      "Las páginas recopiladas no ofrecen cifras de visualizaciones consistentes en ambas plataformas. Me gusta, comentarios y vistas son medidas distintas: aquí no inventamos una clasificación.",
    visitInstagram: "Visitar Instagram",
    visitFacebook: "Visitar Facebook",
    coverage: "Estado del archivo",
    coverageNote:
      "Se recopilaron las 213 páginas de Instagram visibles durante la colección. Facebook sigue siendo parcial. Los duplicados entre plataformas se unifican cuando la evidencia es sólida; las coincidencias dudosas se mantienen separadas.",
    pending: "Texto de origen incompleto",
    pendingNote:
      "Solo estaba disponible una vista previa. La historia completa todavía no se ha reconstruido.",
    complete: "historias legibles",
    pendingCount: "vistas previas incompletas",
    merged: "historias en ambas redes",
    savedIntro:
      "Algunas páginas para volver a visitar. Guardadas solo en este navegador.",
    savedEmpty: "Tu lista de lectura sigue abierta.",
    savedHint: "Guarda una historia que se quede contigo.",
    footer:
      "Un homenaje editorial independiente a una familia en el camino. Las historias y fotografías pertenecen a sus creadores originales.",
    footerNote: "Edición preliminar · Fuentes enlazadas · Sin seguimiento",
    archiveStatus: "Estado del archivo",
    waterfalls: "Cascadas",
    hiking: "Senderismo",
    learning: "Aprender",
    truck: "Vivir en Alma",
    cities: "Días de ciudad",
    unknown: "Sin especificar",
    chapterEmpty: "El próximo capítulo está en preparación.",
    emptyGallery: "No hay fotografías para esta selección.",
  },
};
Object.assign(COPY.en, {
  alma: "Meet Alma",
  school: "School without walls",
  camping: "Camps & camping",
  food: "Around the table",
  beaches: "By the water",
  friendship: "Friendship",
  celebrations: "Celebrations",
  follow: "The journey continues",
  followIntro: "Keep up with the Gutmans, in their own words.",
  followInstagram: "Follow on Instagram",
  followFacebook: "Follow on Facebook",
  everyday: "The everyday adventure",
  everydayIntro: "Different ways into the same extraordinary life.",
  almaIntro:
    "The truck that became a home. The home that made another way of living possible.",
  schoolIntro:
    "Languages, practical skills and lessons that travel with the family.",
  fromCollection: "Stories from this chapter of life",
  strip: "Live With Memories Not Dreams",
  campingSub: "Under canvas, beside rivers, together.",
  foodSub: "Shared meals. New flavors. Familiar rituals.",
  beachesSub: "Salt air and unhurried afternoons.",
  schoolSub: "The world on the timetable.",
});
Object.assign(COPY.he, {
  alma: "נעים להכיר, אלמה",
  school: "בית ספר בלי קירות",
  camping: "מחנות וקמפינג",
  food: "מסביב לשולחן",
  beaches: "ליד המים",
  friendship: "חברות",
  celebrations: "חגיגות",
  follow: "המסע ממשיך",
  followIntro: "להמשיך עם משפחת גוטמן, במילים שלה.",
  followInstagram: "לעקוב באינסטגרם",
  followFacebook: "לעקוב בפייסבוק",
  everyday: "ההרפתקה שבשגרה",
  everydayIntro: "עוד דרכים לפגוש את אותם חיים יוצאי דופן.",
  almaIntro: "המשאית שהפכה לבית. הבית שאפשר דרך חיים אחרת.",
  schoolIntro: "שפות, כישורים מעשיים ושיעורים שנוסעים עם המשפחה.",
  fromCollection: "סיפורים מהפרק הזה בחיים",
  campingSub: "באוהל, ליד הנהר, ביחד.",
  foodSub: "ארוחות משותפות, טעמים חדשים וטקסים מוכרים.",
  beachesSub: "אוויר מלוח ואחר צהריים בלי למהר.",
  schoolSub: "העולם כולו במערכת השעות.",
});
Object.assign(COPY.es, {
  alma: "Conoce a Alma",
  school: "Escuela sin paredes",
  camping: "Campamentos",
  food: "Alrededor de la mesa",
  beaches: "Junto al agua",
  friendship: "Amistad",
  celebrations: "Celebraciones",
  follow: "El viaje continúa",
  followIntro: "Sigue a los Gutman, con sus propias palabras.",
  followInstagram: "Seguir en Instagram",
  followFacebook: "Seguir en Facebook",
  everyday: "La aventura cotidiana",
  everydayIntro: "Distintas puertas a una misma vida extraordinaria.",
  almaIntro:
    "El camión que se convirtió en hogar. El hogar que hizo posible otra forma de vivir.",
  schoolIntro:
    "Idiomas, habilidades prácticas y aprendizajes que viajan con la familia.",
  fromCollection: "Historias de este capítulo de la vida",
  campingSub: "Bajo la lona, junto al río, juntos.",
  foodSub: "Comidas compartidas, sabores nuevos y rituales conocidos.",
  beachesSub: "Aire salado y tardes sin prisa.",
  schoolSub: "El mundo en el horario escolar.",
});
Object.assign(COPY.en, {
  mostViewed: "Most viewed on Instagram",
  viewsLabel: "views",
  viewCountNote: "Public Instagram reel counts, captured on",
  viewCountScope:
    "Reels with visible counts are ranked here. Facebook counts are not combined with Instagram, and likes are not treated as views.",
  openMenu: "Open menu",
  closeStory: "Close story",
  skip: "Skip to content",
});
Object.assign(COPY.he, {
  mostViewed: "הנצפים ביותר באינסטגרם",
  viewsLabel: "צפיות",
  viewCountNote: "נתוני צפייה ציבוריים של רילס באינסטגרם, שנאספו בתאריך",
  viewCountScope:
    "הדירוג כולל רילס עם מספר צפיות גלוי. נתוני פייסבוק אינם מאוחדים עם אינסטגרם, ולייקים אינם נחשבים לצפיות.",
  openMenu: "פתיחת תפריט",
  closeStory: "סגירת הסיפור",
  skip: "דילוג לתוכן",
});
Object.assign(COPY.es, {
  mostViewed: "Más vistos en Instagram",
  viewsLabel: "visualizaciones",
  viewCountNote: "Cifras públicas de reels de Instagram, registradas el",
  viewCountScope:
    "Aquí se ordenan los reels con cifras visibles. No se suman datos de Facebook e Instagram ni se confunden los Me gusta con las visualizaciones.",
  openMenu: "Abrir menú",
  closeStory: "Cerrar historia",
  skip: "Ir al contenido",
});
window.PLACES = [
  ["Bariloche", -41.1335, -71.3103, ["Bariloche", "ברילוצ"]],
  ["Arica", -18.4783, -70.3126, ["Arica", "אריקה"]],
  ["Santiago", -33.4489, -70.6693, ["Santiago", "סנטיאגו"]],
  ["Mendoza", -32.8895, -68.8458, ["Mendoza", "מנדוסה"]],
  ["Córdoba", -31.4201, -64.1888, ["Córdoba", "Cordoba", "קורדובה"]],
  ["Cusco", -13.532, -71.9675, ["Cusco", "Cuzco", "קוסקו"]],
  ["Soraypampa", -13.389, -72.57, ["Soraypampa", "סורייפמפה"]],
  ["Ica", -14.0678, -75.7286, ["Ica", "איקה"]],
  ["Sucre", -19.0196, -65.2619, ["Sucre", "סוקרה"]],
  ["Tupiza", -21.4435, -65.7193, ["Tupiza", "טופיזה"]],
  ["Salar de Uyuni", -20.1338, -67.4891, ["Uyuni", "אויוני", "יוני"]],
  ["Hornocal", -23.212, -65.183, ["Hornocal", "הורנוקל"]],
  ["El Chaltén", -49.3315, -72.8863, ["Chaltén", "Chalten", "צ׳לטן", "צלטן"]],
  ["El Bolsón", -41.964, -71.533, ["Bolsón", "Bolson", "בולסון"]],
  ["Ushuaia", -54.8019, -68.303, ["Ushuaia", "אושואיה"]],
  ["Puerto Natales", -51.726, -72.506, ["Natales", "נטאלס"]],
  ["El Calafate", -50.3379, -72.2648, ["Calafate", "קלפטה"]],
  ["Pucón", -39.28, -71.97, ["Pucón", "Pucon", "פוקון"]],
  ["Puerto Montt", -41.469, -72.941, ["Montt", "מונט"]],
  ["Cochabamba", -17.3895, -66.1568, ["Cochabamba", "קוצ׳במבה", "קוצבמבה"]],
];
window.PEOPLE = [
  {
    image: "DVeL1WpCU2h",
    name: {
      en: "The Gutman family",
      he: "משפחת גוטמן",
      es: "La familia Gutman",
    },
    text: {
      en: "The parents and their three children, Yuval, Nitzan and Maayan. Five people learning how to share a small home and a very big world.",
      he: "ההורים ושלושת הילדים, יובל, ניצן ומעין. חמישה אנשים שלומדים לחלוק בית קטן ועולם גדול מאוד.",
      es: "Los padres y sus tres hijos, Yuval, Nitzan y Maayan. Cinco personas aprendiendo a compartir una casa pequeña y un mundo enorme.",
    },
    topic: "people",
  },
  {
    image: "C8So7mmROYu",
    name: { en: "Boaz", he: "בועז", es: "Boaz" },
    text: {
      en: "From the search for a truck in Arica to repairs on the roadside, Boaz helps turn the family’s home-on-wheels dream into something they can actually drive.",
      he: "מהחיפוש אחר משאית באריקה ועד לתיקונים בצד הדרך, בועז עוזר להפוך את חלום הבית על גלגלים למשהו שאפשר באמת לנסוע בו.",
      es: "Desde la búsqueda del camión en Arica hasta las reparaciones al borde del camino, Boaz ayuda a convertir el sueño de una casa rodante en algo que realmente pueden conducir.",
    },
    query: "Boaz",
  },
  {
    image: "DR0oHCbDCSO",
    name: {
      en: "The young explorers",
      he: "החוקרים הצעירים",
      es: "Los jóvenes exploradores",
    },
    text: {
      en: "Yuval, Nitzan and Maayan grow through friendships, new languages and hands-on discoveries. In these stories, learning rarely stays inside a classroom.",
      he: "יובל, ניצן ומעין גדלים דרך חברויות, שפות חדשות וגילויים מעשיים. בסיפורים האלה, הלמידה כמעט אף פעם לא נשארת בכיתה.",
      es: "Yuval, Nitzan y Maayan crecen entre amistades, nuevos idiomas y descubrimientos prácticos. Aquí, el aprendizaje rara vez se queda en un aula.",
    },
    topic: "learning",
  },
  {
    image: "DEIQsM6pME8",
    name: { en: "Alma", he: "אלמה", es: "Alma" },
    text: {
      en: "Not just a vehicle: their kitchen, sleeping spaces and shelter. Alma is the truck that became the family’s traveling home.",
      he: "לא רק כלי רכב: מטבח, מקומות שינה ומחסה. אלמה היא המשאית שהפכה לבית הנודד של המשפחה.",
      es: "No es solo un vehículo: es cocina, espacios para dormir y refugio. Alma es el camión que se convirtió en el hogar viajero de la familia.",
    },
    topic: "truck",
  },
  {
    image: "DalGAcyMkc1",
    name: {
      en: "Friends along the way",
      he: "החברים שבדרך",
      es: "Amigos del camino",
    },
    text: {
      en: "A shared meal, a parking space, an unexpected invitation. From Noam and Ricardo to families met on the road, generosity keeps changing the itinerary.",
      he: "ארוחה משותפת, מקום חניה, הזמנה מפתיעה. מנועם וריקרדו ועד למשפחות שפגשו בדרכים, הנדיבות ממשיכה לשנות את המסלול.",
      es: "Una comida compartida, un lugar para estacionar, una invitación inesperada. De Noam y Ricardo a las familias del camino, la generosidad cambia el itinerario.",
    },
    topic: "people",
  },
  {
    image: "DEd5zkYMYlR",
    name: {
      en: "More generations, more memories",
      he: "עוד דורות, עוד זיכרונות",
      es: "Más generaciones, más recuerdos",
    },
    text: {
      en: "When grandparents join the journey, the road becomes a meeting place for generations. Ordinary time together becomes part of the adventure.",
      he: "כשהסבים מצטרפים למסע, הדרך הופכת למפגש בין דורות. הזמן הפשוט ביחד נעשה חלק מההרפתקה.",
      es: "Cuando los abuelos se suman al viaje, el camino reúne a generaciones. El tiempo cotidiano juntos se convierte en parte de la aventura.",
    },
    query: "grandparents",
  },
];
window.QUIZ = [
  {
    id: "DF0ycjvvGuL",
    q: {
      en: "What is the family’s home on wheels called?",
      he: "איך נקרא הבית של המשפחה על גלגלים?",
      es: "¿Cómo se llama la casa rodante de la familia?",
    },
    options: ["Alma", "Luna", "Estrella", "Maya"],
    answer: 0,
  },
  {
    id: "C8OAuyPMgZY",
    q: {
      en: "Which Chilean city did Boaz travel to to buy the truck?",
      he: "לאיזו עיר בצ׳ילה נסע בועז לרכוש את המשאית?",
      es: "¿A qué ciudad chilena viajó Boaz para comprar el camión?",
    },
    options: ["Santiago", "Arica", "Pucón", "Puerto Montt"],
    answer: 1,
  },
  {
    id: "DalGAcyMkc1",
    q: {
      en: "What was the surprise behind the “history museum” outing?",
      he: "איזו הפתעה הסתתרה מאחורי הטיול ל״מוזיאון ההיסטוריה״?",
      es: "¿Qué sorpresa escondía la salida al «museo de historia»?",
    },
    options: {
      en: [
        "A boat trip",
        "A cooking class",
        "An amusement park",
        "A train ride",
      ],
      he: ["טיול בסירה", "סדנת בישול", "לונה פארק", "נסיעה ברכבת"],
      es: [
        "Un paseo en barco",
        "Una clase de cocina",
        "Un parque de diversiones",
        "Un viaje en tren",
      ],
    },
    answer: 2,
  },
  {
    id: "DZTa_ZusByA",
    q: {
      en: "What simple errand in Tupiza turned into a new friendship?",
      he: "איזה סידור פשוט בטופיזה הפך לחברות חדשה?",
      es: "¿Qué trámite sencillo en Tupiza se convirtió en una amistad?",
    },
    options: {
      en: [
        "Buying fuel",
        "Changing money",
        "Fixing a tire",
        "Finding a campsite",
      ],
      he: ["קניית דלק", "המרת כסף", "תיקון צמיג", "חיפוש חניון"],
      es: [
        "Cargar combustible",
        "Cambiar dinero",
        "Arreglar una rueda",
        "Buscar un camping",
      ],
    },
    answer: 1,
  },
  {
    id: "DZz3g7fMA2Y",
    q: {
      en: "Which colorful mountain appears in the journey?",
      he: "איזה הר צבעוני מופיע במסע?",
      es: "¿Qué montaña de colores aparece en el viaje?",
    },
    options: ["Hornocal", "Everest", "Fuji", "Kilimanjaro"],
    answer: 0,
  },
];
